PROG_NAME = ./prog
CC = gcc
CFLAGS = -std=c11 -pedantic -Wall -Wextra

all: ./iohelp.c ./array.c ./circular_list.c ./main.c
	$(CC) $(CFLAGS) ./iohelp.c ./array.c ./circular_list.c ./main.c -o $(PROG_NAME)
