PROGNAME = ./prog
CC = g++
CFLAGS = -g -std=c++2a -pedantic -Wall -Wextra
SRC = ./main.cpp

all: $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(PROGNAME)

complex: ./complex.cpp
	$(CC) $(CFLAGS) ./complex.cpp -o ./complex

